### ISSUE TITLE
i dont know why the map dont show up

### ISSUE THREAD

**Issue by Ayman-Waid** [ThuHoang2312/Runalyze#40]

**Comment by ThuHoang2312** [comment]
Please check the instruction in the README on how to setup the project. Have you add the API_KEY for the map?

**Comment by Ayman-Waid** [comment]
Thank you for your response , the map is working fine now , the problem i
think was beacauce i just set up my cloud account

**Comment by Ayman-Waid** [comment]
Hey , please can you help me to add a functionalty to the code , i want to
allow to the user to add her way in the run screen map by clicking or
searching in the map ald adding way points so he van on the end to build a
route in the map

**Comment by ThuHoang2312** [comment]
Hi, you can fork the project to your own repository to develop new features yourself. We have stopped developing the project.

**Comment by Ayman-Waid** [comment]
Ok, thanks for the reply.
